FROM debian:bullseye

RUN dpkg --add-architecture arm64 && \
    dpkg --add-architecture armhf
RUN apt-get update

RUN apt-get install -y curl git build-essential gcc-multilib musl-tools musl-dev musl && \
    apt-get install -y crossbuild-essential-armhf crossbuild-essential-arm64

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin/:${PATH}"
RUN rustup target add aarch64-unknown-linux-musl && \
    rustup target add arm-unknown-linux-musleabihf

RUN mkdir /.cargo && \
    echo '[target.aarch64-unknown-linux-musl]\nlinker = "aarch64-linux-musl-gcc"' > /.cargo/config && \
    echo '[target.arm-unknown-linux-musleabihf]\nlinker = "arm-linux-musleabihf-gcc"' >> /.cargo/config

RUN mkdir /build
ENV CARGO_TARGET_DIR /build
ENV CARGO_HOME /build/cache

RUN mkdir /src

WORKDIR /src
CMD ["/src/docker/docker-build-arm.sh"]
